- name: Adds glusterfs clients
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-client
    - glusterfs-common
    - attr

- name: Creates mountpoint if required
  file:
    path: "{{ elasticsearch_snapshot_mount_point }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0775

- name: Ensure remote fs is mounted
  mount:
    fstype: glusterfs
    name: "{{ elasticsearch_snapshot_mount_point }}"
    src: "{{ elasticsearch_snapshot_device }}"
    state: mounted

