- include: check_vars.yml
  tags: ['elasticsearch', 'check']

- include: elasticsearch.yml
  tags: ['elasticsearch']

- include: elasticsearch-fs-snaps.yml
  tags: ['elasticsearch', 'elasticsearch:snapshots']
  when: elasticsearch_snapshot_mount_point and elasticsearch_snapshot_device
